language: node_js
os:
  - windows
  - linux
node_js:
  - "10"
  - "12"
env:
  global:
    - CXX=g++-4.8
install:
  - npm version
  - npm install
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
